'''author@esilgard'''
## global strings for output dictionaries ##
ERRS = "errors"
REPORTS = "reports"
NAME = "name"
TABLE = "table"
TABLES = "tables"
VALUE = "value"
FIELDS = "fields"
REPORT = "report"
CONFIDENCE = "confidence"
VERSION = "algorithmVersion"
STARTSTOPS = "startStops"
KEY = "recordKey"
START = "startPosition"
STOP = "stopPosition"
PATHOLOGY_TABLE = "Pathology"
ERR_STR = "errorString"
ERR_TYPE = "errorType"
ALL = "ALL"
UNK = "UNK"
CLASS_DZ_GROUP = "ClassifiedDiseaseGroup"
RPT_TABLE = "EngineReportInfo"
